server:
  port: 0

spring:
  application:
    name: excel-service
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.200.145.199:5432/scm
    characterEncoding: UTF-8
    username: admin
    password: 1234
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  config-location: classpath:config/myBatis.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.37.155.50:8761/eureka